### ISSUE TITLE
Submit to NPM

### ISSUE THREAD

**Issue by Bluskript** [AkryumInfinitum/vue-virtual-scroller#27]
It would be nice for this to be submitted to the NPM registry, since the Github Package Repository is less convenient and requires authentication.

**Comment by EricRabil** [comment]
I agree, I'll start publishing to NPM. I'd love to get a GitHub action going at some point that automagically publishes different branches.

**Comment by EricRabil** [comment]
https://www.npmjs.com/package/@akryuminfinitum/vue-virtual-scroller
